{% set name = "markdown-oxide" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Feel-ix-343/markdown-oxide/archive/v{{ version }}.tar.gz
  sha256: b614e5a8fb7fd1fb822b11ab106b9c83ebd1bed4e24ab4d344ec1140b273a6d7

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - markdown-oxide &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b markdown-oxide   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im markdown-oxide.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/Feel-ix-343/markdown-oxide
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Robust, Minimalist, Unbundled PKM for your favorite text-editor through the LSP
  dev_url: https://github.com/Feel-ix-343/markdown-oxide

extra:
  recipe-maintainers:
    - danielnachun
